require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe FriendsController do

  def mock_friend(stubs={})
    @mock_friend ||= mock_model(Friend, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all friends as @friends" do
      Friend.stub(:all) { [mock_friend] }
      get :index
      assigns(:friends).should eq([mock_friend])
    end
  end

  describe "GET show" do
    it "assigns the requested friend as @friend" do
      Friend.stub(:find).with("37") { mock_friend }
      get :show, :id => "37"
      assigns(:friend).should be(mock_friend)
    end
  end

  describe "GET new" do
    it "assigns a new friend as @friend" do
      Friend.stub(:new) { mock_friend }
      get :new
      assigns(:friend).should be(mock_friend)
    end
  end

  describe "GET edit" do
    it "assigns the requested friend as @friend" do
      Friend.stub(:find).with("37") { mock_friend }
      get :edit, :id => "37"
      assigns(:friend).should be(mock_friend)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created friend as @friend" do
        Friend.stub(:new).with({'these' => 'params'}) { mock_friend(:save => true) }
        post :create, :friend => {'these' => 'params'}
        assigns(:friend).should be(mock_friend)
      end

      it "redirects to the created friend" do
        Friend.stub(:new) { mock_friend(:save => true) }
        post :create, :friend => {}
        response.should redirect_to(friend_url(mock_friend))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved friend as @friend" do
        Friend.stub(:new).with({'these' => 'params'}) { mock_friend(:save => false) }
        post :create, :friend => {'these' => 'params'}
        assigns(:friend).should be(mock_friend)
      end

      it "re-renders the 'new' template" do
        Friend.stub(:new) { mock_friend(:save => false) }
        post :create, :friend => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested friend" do
        Friend.stub(:find).with("37") { mock_friend }
        mock_friend.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :friend => {'these' => 'params'}
      end

      it "assigns the requested friend as @friend" do
        Friend.stub(:find) { mock_friend(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:friend).should be(mock_friend)
      end

      it "redirects to the friend" do
        Friend.stub(:find) { mock_friend(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(friend_url(mock_friend))
      end
    end

    describe "with invalid params" do
      it "assigns the friend as @friend" do
        Friend.stub(:find) { mock_friend(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:friend).should be(mock_friend)
      end

      it "re-renders the 'edit' template" do
        Friend.stub(:find) { mock_friend(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested friend" do
      Friend.stub(:find).with("37") { mock_friend }
      mock_friend.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the friends list" do
      Friend.stub(:find) { mock_friend }
      delete :destroy, :id => "1"
      response.should redirect_to(friends_url)
    end
  end

end
